// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:0d56e3a3-3610-4382-9e19-bfdaf5952ee7",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_u7zMcPPhk",
    "aws_user_pools_web_client_id": "15bv4m9tblch4hcr05ttl8acc1",
    "oauth": {}
};


export default awsmobile;
