export const EMPTY = '';
export const EMPTY_ARRAY: object[] = [];
export const FIRST_ELEMENT = 0;
export const API_KEY = 'apiKey';
export const REGISTRY_ID = 'registryId';
export const AUTHORISED = 'authorised';
export const REGISTRIES = 'registries';
export const USER = 'user';
export const LINK = 'link';